name: ignite_flutter_todo_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

  #Gerencia de estado
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  mobx_codegen: ^2.0.4

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

flutter:

  uses-material-design: true